Datasets:
  train:
    root: /kaggle/input/
    type: MVTec
    split: 0.8
  eval:
    root: /kaggle/input/
    type: MVTec
  imagenet:
    root: /kaggle/input/imagenet-object-localization-challenge/ILSVRC/Data/CLS-LOC/train/
    type: imagenet
    teacher_input: 512
    grayscale_ratio: 0.3


Model:
  checkpoints: ckptMedium/best_teacher.pth
  model_size: M
  batch_size: 1
  channel_size: 384
  input_size: 512
  iterations: 50000
  with_bn: false
  


print_freq: 100
category: dronodatrunway
normalized_ratio: 0.1
combined_mst_ratio: 0.5
combined_mae_ratio: 0.5
checkpoints_type: auroc
seed: 42
ckpt_dir: ckptMedium